### ISSUE TITLE
Hostapd blocked by rfkill

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/meshmedia#1]
For now SSH in and `rfkill unblock wifi` but we need to find out who is fighting for the radio and disable it. It's [probably NetworkManager](https://github.com/tomeshnet/prototype-cjdns-pi/blob/master/scripts/install2#L145-L151) or it can be [wpa_supplicant](https://github.com/dweb-camp-2019/meshnet/blob/master/testnet/install#L9-L16).

**Comment by benhylau** [comment]
@YurkoWasHere probably knows something about this

**Comment by YurkoWasHere** [comment]
The "fix" was added back in the master branch

https://github.com/tomeshnet/prototype-cjdns-pi/blob/master/scripts/hostapd/install#L163

**Comment by YurkoWasHere** [comment]
Context: I think this issue was introduced in buster, and as far as i know there is no way around it.

**Comment by benhylau** [comment]
Fixed, thanks @YurkoWasHere
